# Generated by Django 3.1.4 on 2021-02-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=4)),
                ('account_holder_name', models.CharField(max_length=50)),
                ('customer', models.CharField(max_length=30)),
                ('job_name', models.CharField(max_length=30)),
                ('bin', models.CharField(max_length=30)),
                ('ext', models.CharField(max_length=30)),
                ('valid_filename', models.CharField(max_length=30)),
                ('card_quantity', models.CharField(max_length=10)),
                ('carrier_qty', models.CharField(max_length=10)),
                ('data_recorded', models.CharField(max_length=30)),
                ('expected_ship_date', models.DateTimeField(verbose_name='date published')),
                ('cust_filename', models.CharField(max_length=30)),
                ('shipment_quantity', models.CharField(max_length=30)),
                ('shipment_date', models.DateTimeField(verbose_name='date published')),
                ('special_notes', models.CharField(max_length=30)),
                ('last_update_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
