# Generated by Django 3.1.4 on 2021-02-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='expected_ship_date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_update_date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='shipment_date',
            field=models.CharField(max_length=30),
        ),
    ]
